export const locationOptions = {
    "-1": [],
    17: [
        ["242", "AJDOVŠČINA Tovarniška cesta 26"],
        ["241", "AJDOVŠČINA Tovarniška cesta 26 TESTIRNICA"],
        ["203", "Idrija, Mestni trg 2, testirnica"],
        ["235", "ILIRSKA BISTRICA Šercerjeva cesta 17"],
        ["211", "ILIRSKA BISTRICA Šercerjeva cesta 17 TESTIRNICA"],
        ["120", "KOPER Bertoki vadbena površina"],
        ["119", "Koper, Ljubljanska cesta 6"],
        ["117", "Koper, Ljubljanska cesta 6, testirnica"],
        ["121", "Nova Gorica, Avtobusna postaja"],
        ["126", "Nova Gorica, mejni prehod Vrtojba, vadbena površina"],
        ["210", "Nova gorica, parkirišče šole vožnje"],
        ["209", "Nova Gorica, Trg Edvarda Kardelja 1"],
        [
        "123",
        "Nova Gorica, Trg Edvarda Kardelja 1, pritličje soba 13, testirnica",
        ],
        ["225", "POSTOJNA Kazarje 10 EPIC"],
        ["226", "POSTOJNA Kazarje 10 EPIC TESTIRNICA"],
        ["219", "SEŽANA Ulica Mirka Pirca 4"],
        ["218", "SEŽANA Ulica Mirka Pirca 4 TESTIRNICA"],
        ["234", "TOLMIN Tumov drevored 4"],
        ["125", "Tolmin, Tumov drevored 4, soba IIN23, testirnica"],
        ["118", "Za izpit s tolmačem Koper, Ljubljanska 6, testirnica"],
        [
        "124",
        "Za izpit s tolmačem Nova Gorica, Trg Edvarda Kardelja 1, testirnica",
        ],
        ["227", "Za izpit z tolmačem POSTOJNA Kazarje 10 EPIC TESTIRNICA"],
    ],
    18: [
        ["173", "Domžale, Ljubljanska cesta 71"],
        ["174", "DOMŽALE Ljubljanska cesta 71 TESTIRNICA"],
        ["176", "Ig"],
        ["171", "Jesenice, Cesta železarjev 6a"],
        ["168", "JESENICE Cesta železarjev 6a TESTIRNICA"],
        ["223", "KRANJ Kolodvorska cesta 5"],
        ["222", "KRANJ Kolodvorska cesta 5 TESTIRNICA"],
        ["221", "LJUBLJANA Cesta dveh cesarjev 176"],
        ["236", "LJUBLJANA Cesta dveh cesarjev 176 TESTIRNICA"],
        ["178", "Ljubljana, Ježica"],
        ["184", "Vrhnika"],
        ["224", "Za izpit s tolmačem KRANJ Kolodvorska cesta 5 TESTIRNICA"],
        ["237", "Za izpit s tolmačem LJUBLJANA Cesta dveh cesarjev 176 TESTIRNICA"],
    ],
    19: [
        [150, "Ljubečna, Cesta v Celje 14"],
        [148, "Ljubečna, Cesta v Celje 14, testirnica"],
        [151, "1 Za izpit s tolmačem CELJE Ljubečna Cesta v Celje 14 TESTIRNICA"],
        [157, "Trbovlje, Mestni trg 4"],
        [156, "Trbovlje, Mestni trg 4, testirnica"],
        [167, "2 Za izpit s tolmačem TRBOVLJE Mestni trg 4  TESTIRNICA"],
        [228, "3 VELENJE Koroška cesta 62a"],
        [229, "3 VELENJE Koroška cesta 62a TESTIRNICA"],
        [230, "3 Za izpit s tolmačem VELENJE Koroška cesta 62a TESTIRNICA"],
        [160, "Slovenj Gradec, Meškova ulica 21"],
        [158, "Slovenj Gradec, Meškova ulica 21, testirnica"],
        [166, "4 Za izpit s tolmačem SLOVENJ GRADEC Meškova 21  TESTIRNICA"],
        [149, "Laško, Poženelova ulica 22"],
        [153, "Ločica ob Savinji, Ločica ob Savinji 49"],
        [162, "Ravne na Koroškem, Čečovje 12a, testirnica"],
        [152, "Slovenske Konjice, Tattenbachova ulica 2a"],
        [154, "ŠENTJUR Cesta na kmetijsko šolo 9"],
        [155, "ŠMARJE PRI JELŠAH Obrtniška ulica 4"],
    ],
    20: [
        ["-1", "Vse lokacije"],
        ["231", "BREŽICE Izobraževalno vadbeni center Bizeljska cesta 45 TEORIJA"],
        ["232", "BREŽICE Izobraževalno vadbeni center Bizeljska cesta 45 VOŽNJA"],
        ["191", "ČRNOMELJ TESTIRNICA Ulica Otona Župančiča 4"],
        ["190", "ČRNOMELJ VOŽNJA Ulica Otona Župančiča 4"],
        ["195", "Kočevje, ŠD GAJ, Trg zbora odposlancev 30, testirnica"],
        ["194", "KOČEVJE VADBENA POVRŠINA HERBBY Novomeška cesta"],
        ["193", "KOČEVJE VOŽNJA Cesta na stadion 7"],
        ["204", "Krško, Žadovinek 36, testirnica"],
        ["205", "Krško, Žadovinek 36, vožnja"],
        ["187", "NOVO MESTO BTC ČEŠČA VAS 40 samo za kat B96 BE C CE D1 D F"],
        [
        "186",
        "NOVO MESTO UE Defranceschijeva 1 TESTIRNICA vhod z zadnje strani stavbe",
        ],
        ["185", "NOVO MESTO UE Defranceschijeva 1 VOŽNJA"],
        ["202", "Sevnica, Prvomajska 8"],
        ["192", "Za izpit s tolmačem ČRNOMELJ Ulica Otona Župančiča 4"],
        [
        "196",
        "Za izpit s tolmačem Kočevje, ŠD GAJ, Trg zbora odposlancev 30, testirnica",
        ],
        ["208", "Za izpit s tolmačem Krško, Žadovinek 36, testirnica"],
        [
        "188",
        "Za izpit s tolmačem Novo mesto, UE Defranceschijeva 1, testirnica",
        ],
    ],
    21: [
        [212, "Maribor, Cesta k Tamu 11"],
        [213, "Maribor, Cesta k Tamu 11, testirnica"],
        [147, "Maribor, Zolajeva ulica 12, vadbena površina Tezno"],
        [138, "Murska Sobota, Noršinska ulica 8"],
        [142, "Murska Sobota, Noršinska ulica 8, testirnica"],
        [143, "Ormož, Vrazova ulica 12, testirnica"],
        [146, "PTUJ Dornavska cesta 22B "],
        [144, "PTUJ Dornavska cesta 22B A KAT"],
        [145, "PTUJ Dornavska cesta 22B  CCE KAT"],
        [141, "PTUJ  Dornavska cesta 22B TESTIRNICA"],
        [136, "SLOVENSKA BISTRICA Partizanska 22  TESTIRNICA"],
        [139, "Za izpit s tolmačem Murska Sobota, Noršinska ulica 8, testirnica"],
        [140, "Za izpit s tolmačem, Ptuj, Dornavska cesta 22B, testirnica"],
        [214, "Za izpit s tolmačem teorija Maribor, Cesta k Tamu 11"],
    ],
};
